apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: geo-3d-otel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geo-3d-otel
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 80
