apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hpa.yaml
- deployment.yaml
- service.yaml
images:
- name: geo3d-image
  newName: ghcr.io/efumagal/geo-3d-otel
  newTag: 20230807-1022
namespace: test-apps
