apiVersion: v1
kind: Service
metadata:
  name: geo-3d-otel
spec:
  type: ClusterIP
  selector:
    app: geo-3d-otel
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http